=== Inadequado4192/RWML-Public/Languages/Scheme.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ModInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="authors">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="li" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="nickname"/>
                    <xs:element type="xs:string" name="fullname" minOccurs="0"/>
                    <xs:element name="links" minOccurs="0">
                      <xs:complexType>
                        <xs:all>
                          <xs:element type="xs:string" name="discord" minOccurs="0"/>
                          <xs:element type="xs:string" name="twitter" minOccurs="0"/>
                          <xs:element type="xs:string" name="instagram" minOccurs="0"/>
                          <xs:element type="xs:string" name="facebook" minOccurs="0"/>
                          <xs:element type="xs:string" name="reddit" minOccurs="0"/>
                          <xs:element type="xs:string" name="steam" minOccurs="0"/>
                        </xs:all>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:dateTime" name="lastUpdate"/>
        <xs:element type="xs:string" name="note" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Inadequado4192/RWML-Public/Languages/Zombieland/Ukrainian (Українська)/About.xml
<?xml version="1.0" encoding="UTF-8"?>

<ModInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Inadequado4192/RWML-Public/master/Languages/Scheme.xsd">
    <authors>
        <li>
            <nickname>Inadequado</nickname>
            <links>
                <discord>inadequado4192</discord>
                <instagram>https://www.instagram.com/inadequado4192</instagram>
                <steam>https://steamcommunity.com/id/inadequado4192</steam>
            </links>
        </li>
    </authors>
    <lastUpdate>2023-11-22T15:00:55.432Z</lastUpdate>
    <note>Наразі перекладено всі рядки, але переклад неточний.</note>
</ModInfo>

=== Inadequado4192/RWML-Public/Test-About.xml
<?xml version="1.0" encoding="UTF-8"?>

<ModInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./Scheme.xsd">
    <authors>
        <li>
            <nickname>Inadequado</nickname>
            <fullname>K.V.V.</fullname>
            <links>
                <instagram>https://www.instagram.com/inadequado4192</instagram>
                <discord>inadequado4192</discord>
            </links>
        </li>
    </authors>
    <lastUpdate>2023-09-27T13:18:50.602Z</lastUpdate>
</ModInfo>
